### ISSUE TITLE
Symfony Console & DI

### ISSUE THREAD

**Issue by mnapoli** [somos/framework#32]
I wanted to bring your attention to a problem I've been facing over and over and that we are currently trying to solve in Piwik: using dependency injection with Symfony console.

Basically the problem is that commands need to be instantiated to be registered in Symfony's console. Because of that, using DI in commands means all the dependency graph might be created just to boot up the console, cause [several issues](https://github.com/piwik/piwik/pull/7175#issuecomment-74193939).

With your architecture (actions instead of commands), will you be facing the same problem? If not, how do you do it ;)?

For reference:

- the Symfony ticket discussing this: https://github.com/symfony/symfony/issues/12063
- a possible solution that is being discussed for Piwik: https://github.com/piwik/piwik/pull/7175

**Comment by mvriel** [comment]
With Somos' current architecture we defer the loading of dependencies until a later point. The basic idea behind somos is that you have Actions and Responders. Each Action is a callable, or actually called using `call()` in the container and we have a single Symfony\Console\Command that does nothing else but in its execute call a callable that triggers the InvokeAction message in the Command Bus. The InvokeAction handler then uses the `call()` method of the container to execute the action and subsequently the responder and at that moment dependencies are loaded.

**Comment by mnapoli** [comment]
OK, so the commands configuration/descriptions are separate from the actual code (which isn't even a "cli command" since it's just an "action). Cool!

So basically it works like HTTP routing right, except for the CLI?

**Comment by mvriel** [comment]
It is exactly that; the basic idea behind Somos is that there is no Controller, there is no Command; there is just an Action and a Responder. The Action can be shared between the web or cli since it doesn't contain any references to the console or requests and responses; the responders can differ depending on the method communication.

But the responders are only pass-throughs to the OutputInterface or Response object; it is this seggregation of responsibilities that is Somos' Unique Selling Point as far as I am concerned
